### ISSUE TITLE
Add Kernel.UUID for eventual UUID primary key in mapper

### ISSUE THREAD

**Issue by jc00ke** [lotus/utils#60]
Proposing we add `UUID` so in the mapper we can have

```ruby
  mapper = Lotus::Model::Mapper.new do
  collection :books do
    entity Book
   
    attribute :id, UUID   
    attribute :title, String
  end
end
```

Thoughts?

**Comment by jodosha** [comment]
@jc00ke Thanks for opening this ticket. We are already discussing about custom coercions in a separated GH issue. https://github.com/lotus/model/issues/36

I recognize that `UUID` is a _"type"_ as an output of an algorithm. We represent it as a string, but there is difference between `"hello"` and `"20c61826-48c1-4f52-a6fd-f1de26ce0f6a"`.

However, this can't be implemented as a coercion. The rule of thumb for `Utils::Kernel` is: try to convert the input into a specific type or raise a `TypeError`. This guideline works well with _"strong types"_, eg primitives like Integer or Date.

The problem with `UUID` is to apply this concept. What to do if I get an integer as input? What to do when a non-UUID string is given? Probably we'll raise an error.

In the end, the only input that won't make this function to blow is an object that respond to `#to_str` or `#to_s` and returns a valid UUID. But is it worth to have it around?

Semantically, it looks more like a validation than a coercer. Also, because this would be only introduced because of the mapper, I'm keen to close this ticket and to continue the discussion over there.
