### ISSUE TITLE
Date/Time formatters

### ISSUE THREAD

**Issue by davydovanton** [lotus/utils#97]
Hello.
I want tot help with [this task from trello](https://trello.com/c/q7WEs640/92-date-time-formatters) (Date/Time formatters). Do you want to see smth like [`Date`](http://api.rubyonrails.org/classes/Date.html) and [`Time`](http://api.rubyonrails.org/classes/Time.html) rails helpers?

**Comment by jodosha** [comment]
@davydovanton Hey thanks for going through the Trello board.

That feature is a for `lotus-helpers` (see the ticket label in Trello), not for `lotus-utils`. It isn't planned yet, because it involves i18n, which needs a bigger evaluation on how to support it in Lotus.

Because of our open process, you're free to suggest solutions that can work both for `lotus-helpers` in isolation and `lotusrb` (for full stack web apps). I want to point out that this isn't a priority at this time. All the discussions are delayed until future releases.

PS: In order to keep a good signal/noise ratio, please don't open issues that aren't bugs or improvements. Because features require a major thinking, tickets aren't the right way to start a conversation.

Thanks for understanding. :smile: :+1:

**Comment by davydovanton** [comment]
I understand. Thanks for explanation again! :blush:
